name: Test and Build

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Use Rust
        run: rustup component add rustfmt
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Check formatting
        run: npm run lint --workspaces --if-present
      - name: Run tests
        run: npm run test --workspaces --if-present
      - name: Build WASM library
        run: npm run build --workspaces --if-present

  build-native:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: aarch64-apple-darwin
            build: |
              cd bandersnatch/native-binding
              cargo build --release --target aarch64-apple-darwin
              mkdir -p ../npm/darwin-arm64
              cp target/aarch64-apple-darwin/release/libbandersnatch_native.dylib ../npm/darwin-arm64/bandersnatch.darwin-arm64.node
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            build: |
              cd bandersnatch/native-binding
              cargo build --release --target x86_64-unknown-linux-gnu
              mkdir -p ../npm/linux-x64-gnu
              cp target/x86_64-unknown-linux-gnu/release/libbandersnatch_native.so ../npm/linux-x64-gnu/bandersnatch.linux-x64-gnu.node

    runs-on: ${{ matrix.settings.host }}
    name: Build native - ${{ matrix.settings.target }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Rust
        uses: dtolnay/rust-action@stable
        with:
          targets: ${{ matrix.settings.target }}
      - name: Build
        run: ${{ matrix.settings.build }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bindings-${{ matrix.settings.target }}
          path: bandersnatch/npm/*/*.node
          if-no-files-found: error
